general {
    ignore_dbus_inhibit = false
}

listener {
    timeout = 120
    on-timeout = pidof hyprlock || /usr/local/bin/hd-launch-screensaver
}

listener {
    timeout = 240
    on-timeout = /usr/local/bin/hd-kill-screensaver & hyprlock
}

listener {
    timeout = 245
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })' && brightnessctl -r
}

