[opener]

# Video

mpv_open = [
  { run = 'mpv %s', orphan = true, desc = "Open (MPV)" },
]

# Audio

audacious_open = [
  { run = 'audacious %s', orphan = true, desc = "Open (Audacious)" },
]

audacious_enqueue = [
  { run = 'audacious --enqueue %s', orphan = true, desc = "Enqueue (Audacious)" },
]

# Images

imv_open = [
  { run = 'imv-wayland %s', orphan = true, desc = "Open (Imv)" },
]

[open]

rules = [
  { mime = "video/*", use = "mpv_open" },
  { mime = "audio/*", use = ["audacious_open", "audacious_enqueue"] },
  { mime = "image/*", use = "imv_open" },
]
